name: hei_survei
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  flutter_riverpod: ^2.3.6

  uuid: ^3.0.7
  http: ^1.1.0
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  flutter_quill: ^7.4.3
  syncfusion_flutter_charts: ^22.2.12
  graphql_flutter: ^5.2.0-beta.6
  go_router: ^12.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.1
  intl: ^0.18.1
  midtrans_sdk: ^0.4.0
  easy_sidemenu: ^0.5.0
  flutter_spinkit: ^5.2.0
  dropdown_search: ^5.0.6
  file_picker: ^6.1.1
  firebase_storage: ^11.6.0
  flutter_image_compress: ^1.1.3
  image_picker: ^0.8.2
  flimer: ^1.0.1
  image_compression: ^1.0.4
  url_strategy: ^0.2.0
  syncfusion_flutter_sliders: ^22.2.12
  dotted_border: ^2.1.0
  printing: ^5.12.0
  pdf: ^3.10.8
  firebase_database: ^10.4.0
  firebase_dynamic_links: ^5.4.8
  google_sign_in: ^6.1.6
  firebase_auth: ^4.16.0
  badges: ^3.1.2
  excel: ^4.0.2
  encrypt: ^5.0.3
  # syncfusion_flutter_xlsio: ^22.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/maskot.png
    - assets/google.png
    - assets/logo-klasik.png
    - assets/logo-kartu.png
    - assets/logo-maaf.png
    - assets/logo-tidak.png
    - assets/no-data-katalog.png
    - assets/logo-app.png
    - assets/logo-login.jpg
    - assets/login2.png
    - assets/login4.png
    - assets/signup1.png
    - assets/signup2.png
    - assets/no-draft.png
    - assets/surveyor.png
    - assets/search.png
    - assets/report.png
    - assets/draft.png
    - assets/preview.png
    - assets/beli.png
    - assets/gagal-memuat.png
    - assets/no-trans.png
    - assets/no-trans-midtrans.png
    - assets/logo-bayar.png
    - assets/belum-ada-penarikan.png
    - assets/belum-ada-pembelian.png
    - assets/no-pass.jpg
    - .env
  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
        - asset: fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: fonts/Merriweather-Italic.ttf
          style: italic
        - asset: fonts/Merriweather-Light.ttf
          weight: 300
